#!/bin/bash

window=$(cat /proc/$(xdotool getwindowpid $(xdotool getwindowfocus))/comm)
title=$(xdotool getactivewindow getwindowname)

if [[ $window == "" || $title == "" ]]; then
  echo "Desktop"
  exit 0
fi

echo "$window - $title"
