
name: "en-us"
row_size: 12.25

#  ________________________________________________________________________
# '  ~  |  1  |  2  |  3  |  4  |  5  |  6  |  7  |  8  |  9  |   0  |  -  |
# |------------------------------------------------------------------------|
# | Esc |  Q  |  W  |  E  |  R  |  T  |  Y  |  U  |  I  |  O  |   P  |  =  |
# |------------------------------------------------------------------------|
# | Tab  |  A  |  S  |  D  |  F  |  G  |  H  |  J  |  K  |  L  |  "  |  :  |
# |------------------------------------------------------------------------|
# |  Shift |  Z  |  X  |  C  |  V  |  B  |  N  |  M  |  ,   |  .  | Enter  |
# |------------------------------------------------------------------------|
# |    | Ctl | Alt | Sup |  Space   | BSpace |  <  |  ^  |  v  |  >  |     |
# -------------------------------------------------------------------------
#

key_sizes:
  - [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.25]
  - [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.25]
  - [1.25, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  - [1.75, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.50]
  - [0.5, 1, 1, 1,  2.25, 2, 1, 1, 1, 1, 1]

main_layout:
  - ["Til", "N1", "N2", "N3", "N4", "N5", "N6", "N7", "N8", "N9", "N0","Minus"]
  - ["Esc", "Q",  "W",  "E",  "R",  "T",  "Y",  "U",  "I",  "O",  "P", "Plus" ]
  - ["Tab",  "A",  "S",  "D",  "F",  "G",  "H",  "J",  "K",  "L", "QT", "CLN" ]
  - ["Shft",   "Z",  "X",  "C",  "V",  "B",  "N",  "M", "Com", "Dot",   "Ent" ]
  - [ ~, "Ctl", "Alt", "Sup",  "Space",   "BSpace", "LT", "DN", "UP", "RT", ~ ]

alt_modifier: None
alt_layout_mode: None

exec_commands:

macros:
  Esc: ["Escape"]
  Shft: ["LShift"]
  Ent: ["KP_Enter"]
  Ctl: ["LCtrl"]
  Sup: ["LSuper"]
  Alt: ["LAlt"]
  BSpace: ["BackSpace"]
  Til: ["Oem3"]
  QT: ["Oem7"]
  CLN: ["Oem1"]
  LF: ["Left"]
  RT: ["Right"]
  DN: ["Down"]
  UP: ["Up"]
  Dot: ["Period"]
  Com: ["Comma"]

labels:
  "N1": ["1", "!"]
  "N2": ["2", "@"]
  "N3": ["3", "#"]
  "N4": ["4", "$"]
  "N5": ["5", "%"]
  "N6": ["6", "^"]
  "N7": ["7", "&"]
  "N8": ["8", "*"]
  "N9": ["9", "("]
  "N0": ["0", ")"]
  "Escape": ["Esc"]
  "KP_Enter": ["Enter"]
  "LShift": ["Shift"]
  "LCtrl": ["Ctrl"]
  "LSuper": ["Super"]
  "LAlt": ["Alt"]
  "Oem3": ["`", "~"]
  "Oem7": ["'", "\""]
  "Oem1": [":", ";"]
  "Left": ["<"]
  "Right": [">"]
  "Down": ["v"]
  "Up": ["^"]
  "Period": [".", ">"]
  "Comma": [",", "<"]
  "Minus": ["-", "_"]
  "Plus": ["=", "+"]
