
name: "en-us"
row_size: 12.25

#  ________________________________________________________________________
# '  ~  |  1  |  2  |  3  |  4  |  5  |  6  |  7  |  8  |  9  |   0  |  -  |
# |------------------------------------------------------------------------|
# | Esc |  Q  |  W  |  E  |  R  |  T  |  Y  |  U  |  I  |  O  |   P  |  =  |
# |------------------------------------------------------------------------|
# | Tab  |  A  |  S  |  D  |  F  |  G  |  H  |  J  |  K  |  L  |  "  |  :  |
# |------------------------------------------------------------------------|
# |  Shift |  Z  |  X  |  C  |  V  |  B  |  N  |  M  |  ,   |  .  | Enter  |
# |------------------------------------------------------------------------|
# |    | Ctl | Alt | Sup |  Space   | BSpace |  <  |  ^  |  v  |  >  |  /  |
# -------------------------------------------------------------------------
#

key_sizes:
  - [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.25]
  - [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.25]
  - [1.25, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
  - [1.75, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1.50]
  - [ 1, 1, 1,   2.25,   2, 1, 1, 1, 1, 1 ]

main_layout:
  - ["Oem3", "N1", "N2", "N3", "N4", "N5", "N6", "N7", "N8", "N9", "N0","Minus"]
  - ["Escape", "Q",  "W",  "E",  "R",  "T",  "Y",  "U",  "I",  "O",  "P", "Plus" ]
  - ["Tab",  "A",  "S",  "D",  "F",  "G",  "H",  "J",  "K",  "L", "Oem7", "Oem1" ]
  - ["LShift",   "Z",  "X",  "C",  "V",  "B",  "N",  "M", "Comma", "Period",   "KP_Enter" ]
  - ["LCtrl", "LAlt", "LSuper",  "Space",   "BackSpace", "Left", "Down", "Up", "Right", "Oem2"]

alt_modifier: None
alt_layout_mode: None

exec_commands:

macros:

labels:
  "N1": ["1", "!"]
  "N2": ["2", "@"]
  "N3": ["3", "#"]
  "N4": ["4", "$"]
  "N5": ["5", "%"]
  "N6": ["6", "^"]
  "N7": ["7", "&"]
  "N8": ["8", "*"]
  "N9": ["9", "("]
  "N0": ["0", ")"]
  "Escape": ["Esc"]
  "KP_Enter": ["Enter"]
  "LShift": ["Shift"]
  "LCtrl": ["Ctrl"]
  "LSuper": ["Super"]
  "LAlt": ["Alt"]
  "Oem3": ["`", "~"]
  "Oem7": ["'", "\""]
  "Oem1": [":", ";"]
  "Left": ["<"]
  "Right": [">"]
  "Down": ["v"]
  "Up": ["^"]
  "Period": [".", ">"]
  "Comma": [",", "<"]
  "Minus": ["-", "_"]
  "Plus": ["=", "+"]
  "Oem2": ["/", "?"]
