#!/bin/bash

window=$(xdotool getactivewindow getwindowclassname)
title=$(xdotool getactivewindow getwindowname)

out="$window - $title"

if [ ${#out} -gt 50 ]; then
  out="${out:0:50}..."
fi

echo $out
