
SPACESHIP_PROMPT_ORDER=(dir char)
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_PROMPT_SEPARATE_LINE=false
SPACESHIP_PROMPT_FIRST_PREFIX_SHOW=false

SPACESHIP_DIR_PREFIX=''
SPACESHIP_CHAR_SYMBOL='‣ '
SPACESHIP_USER_SHOW=false

