#!/bin/bash

name=$1

class_idle=""
class_focused="focused"
class_occupied="occupied"

workspace() {
	class=""
	case $(bspc query -D -d "$name" --names) in
	Focused) class=$class_focused ;;
	Occupied) class=$class_occupied ;;
	*) class=$class_idle ;;
	esac

	echo $class
}

workspace
bspc subscribe all | while read -r _; do
	workspace
done
