#!/bin/sh

setup_space() {
  local idx="$1"
  local name="$2"
  local space=
  echo "setup space $idx : $name"

  space=$(yabai -m query --spaces --space "$idx")
  if [ -z "$space" ]; then
    yabai -m space --create
  fi

  yabai -m space "$idx" --label "$name"
}

for _ in $(yabai -m query --spaces | jq '.[].index | select(. > 11)'); do
  yabai -m space --destroy 11
done

setup_space 1 terminal
setup_space 2 browser
setup_space 3 terminal
setup_space 4 any
setup_space 5 any
setup_space 6 any
setup_space 7 music
setup_space 8 social
setup_space 9 email
setup_space 10 slack

