#!/bin/bash

class_idle="idle"
class_focused="focused"
class_occupied="occupied"

workspaces() {
	ws=$(bspc query -D --names)
	active_ws=$(xdotool get_desktop)

	# turn list into json object
	IFS=$'\n' read -r -d '' -a lines <<<"$ws"
	json="{"
	for i in "${!lines[@]}"; do
    line=${lines[$i]}
		class=$class_idle

		if [[ $(bspc query -N -d "$line" | wc -l) -gt 0 ]]; then
			class=$class_occupied
		fi
		if [[ "$i" -eq "$active_ws" ]]; then
			class=$class_focused
		fi

		json="${json}\"${line}\":\"$class\","
	done

	json="${json%,}"
	json="${json}}"

	echo "$json"
}

workspaces
bspc subscribe all | while read -r _; do
	workspaces
done
