[general]
out_dir = ~/.cache/cwal/

[links]
# format: template_name = destination_path | reload_command
colors-btop.theme = ~/.config/btop/themes/colors.theme
colors-mako = ~/.config/mako/config | makoctl reload
colors-quickshell.qml = ~/.config/quickshell/Colors.qml
colors-kitty.conf = ~/.config/kitty/theme.conf
colors-zen.css = ~/.cache/wal/colors-zen.css | for dir in "$HOME"/.zen/*.Default\ Profile; do mkdir -p "$dir/chrome/CSS" && ln -s "$HOME/.cache/wal/colors-zen.css" "$dir/chrome/userChrome.css"; done
colors-niri.kdl = ~/.config/niri/colors.kdl
colors-rofi.rasi = ~/.config/rofi/theme.rasi
colors-discord.css = ~/.cache/wal/colors-discord.css | mkdir -p "$HOME/.config/Vencord/themes" && ln -s "$HOME/.cache/wal/colors-discord.css" "$HOME/.config/Vencord/themes/pywal-vencord.theme.css"
