[general]
out_dir = ~/.cache/cwal/

[links]
# format: template_name = destination_path | reload_command
colors-btop.theme = ~/.config/btop/themes/colors.theme
colors-mako = ~/.config/mako/config | makoctl reload
colors-quickshell.qml = ~/.config/quickshell/Colors.qml
colors-kitty.conf = ~/.config/kitty/theme.conf
colors.json = ~/.cache/wal/colors.json
userChrome.css = ~/.cache/wal/userChrome.css | mkdir -p "$HOME/.zen/*.Default\ Profile/chrome" && ln -sf "$HOME/.cache/wal/userChrome.css" "$HOME/.zen/*.Default\ Profile/chrome/userChrome.css"
colors.kdl = ~/.config/niri/colors.kdl
